### ISSUE TITLE
[Manga not working]

### ISSUE THREAD

**Issue by thatguyaagain** [3174N/anilist-bot#4]
**Describe the bug**

So when i choose manga (naruto) as ig not working!

**Expected behavior**

Anime is working fine but manga nah

**Screenshots**

![IMG_20220113_161956.jpg](https://user-images.githubusercontent.com/61906880/149357670-f5a79b5e-7a37-493e-9866-15b7e7c1f7a7.jpg)

**Comment by 3174N** [comment]
Hi, I think you're in the wrong repository...
I appreciate you effort though.

**Comment by thatguyaagain** [comment]
> Hi, I think you're in the wrong repository...
> I appreciate you effort though.

No I'm using your fork from original one

**Comment by 3174N** [comment]
I'm sorry, what? I do not quite understand what do you mean.

**Comment by thatguyaagain** [comment]
I think you know that the original bot no longer accepts additions to more servers and even a developer does not want to send any ID document to discord....so when I search for other people with the same code I found this and the invite link works I don't know how so I thought there was something different from the original? Lol 
Do yeh apologize.
